packages:
  - packages/*

allowBuilds:
  '@reown/appkit': true
  better-sqlite3: true
  bufferutil: true
  esbuild: true
  keccak: true
  msgpackr-extract: true
  utf-8-validate: true

catalog:
  '@types/node': ^24.12.4
  '@vitejs/plugin-react': ^6.0.2
  tsx: ^4.22.3
  typescript: ^5.9.2
  vite: ^8.0.13
  vite-plus: ^0.1.22

overrides:
  three: ^0.173.0
  'ws@>=8.0.0 <8.20.1': 8.20.1

minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core@0.1.22'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.1.22'
  - '@voidzero-dev/vite-plus-darwin-x64@0.1.22'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.1.22'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.1.22'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.1.22'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.1.22'
  - '@voidzero-dev/vite-plus-test@0.1.22'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.1.22'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.1.22'
  - vite-plus@0.1.22
