export const BUILTIN_APP_TEMPLATES = [
  {
    appName: 'Model',
    fileBase: 'Model',
    scriptAsset: 'Model.js',
    config: {
      scriptFormat: 'module',
      image: {
        url: 'asset://Model.png',
      },
      model: 'asset://Model.glb',
      props: {
        collision: true,
      },
      preload: false,
      public: false,
      locked: false,
      frozen: false,
      unique: true,
      keep: true,
      scene: false,
      disabled: false,
    },
  },
  {
    appName: 'Image',
    fileBase: 'Image',
    scriptAsset: 'Image.js',
    config: {
      scriptFormat: 'module',
      image: {
        url: 'asset://Image.png',
      },
      model: 'asset://Image.glb',
      props: {
        width: 0,
        height: 2,
        fit: 'cover',
        image: null,
        transparent: false,
        lit: false,
        shadows: true,
        placeholder: {
          type: 'image',
          url: 'asset://Image.png',
        },
      },
      preload: false,
      public: false,
      locked: false,
      frozen: false,
      unique: true,
      keep: true,
      scene: false,
      disabled: false,
    },
  },
  {
    appName: 'Video',
    fileBase: 'Video',
    scriptAsset: 'Video.js',
    config: {
      scriptFormat: 'module',
      image: {
        url: 'asset://Video.png',
      },
      model: 'asset://Video.glb',
      props: {
        width: 0,
        height: 2,
        fit: 'cover',
        url: null,
        loop: true,
        autoplay: true,
        transparent: false,
        lit: false,
        shadows: true,
        placeholder: {
          type: 'video',
          url: 'asset://Video.mp4',
        },
      },
      preload: false,
      public: false,
      locked: false,
      frozen: false,
      unique: true,
      keep: true,
      scene: false,
      disabled: false,
    },
  },
  {
    appName: 'Text',
    fileBase: 'Text',
    scriptAsset: 'Text.js',
    config: {
      scriptFormat: 'module',
      image: {
        url: 'asset://Text.png',
      },
      model: 'asset://Text.glb',
      props: {
        width: 200,
        height: 200,
        text: 'Enter text...',
        fontSize: 20,
        fontWeight: 'bold',
        color: '#ffffff',
        transparent: false,
        lit: false,
        shadows: true,
      },
      preload: false,
      public: false,
      locked: false,
      frozen: false,
      unique: true,
      keep: true,
      scene: false,
      disabled: false,
    },
  },
  {
    appName: 'Webview',
    fileBase: 'Webview',
    scriptAsset: 'Webview.js',
    config: {
      scriptFormat: 'module',
      image: {
        url: 'asset://Webview.png',
      },
      model: 'asset://Webview.glb',
      props: {
        url: 'https://www.youtube.com/embed/jfKfPfyJRdk?autoplay=1',
      },
      preload: false,
      public: false,
      locked: false,
      frozen: false,
      unique: true,
      keep: true,
      scene: false,
      disabled: false,
    },
  },
]

export const SCENE_TEMPLATE = {
  appName: '$scene',
  fileBase: '$scene',
  scriptAsset: 'scene.js',
  config: {
    scriptFormat: 'module',
    image: null,
    author: null,
    url: null,
    desc: null,
    model: 'asset://Model.glb',
    props: {
      hour: 4,
      period: 'pm',
      intensity: 1,
      sky: {
        url: 'asset://sky.jpg',
      },
      hdr: {
        url: 'asset://sky.hdr',
      },
      verticalRotation: 40,
      horizontalRotation: 230,
      rotationY: 0,
      fogNear: 450,
      fogFar: 1000,
      fogColor: '#97b4d3',
    },
    preload: true,
    public: false,
    locked: false,
    frozen: false,
    unique: true,
    keep: true,
    scene: true,
    disabled: false,
  },
}

export const BUILTIN_BLUEPRINT_IDS = new Set([
  ...BUILTIN_APP_TEMPLATES.map(template => template.fileBase),
  SCENE_TEMPLATE.fileBase,
])
