export const BUILTIN_APP_TEMPLATES = [
  {
    name: 'Model',
    image: {
      url: 'asset://Model.png',
    },
    model: 'asset://Model.glb',
    script: 'asset://Model.js',
    scriptEntry: 'index.js',
    scriptFiles: {
      'index.js': 'asset://Model.js',
    },
    scriptFormat: 'module',
    props: {
      collision: true,
    },
    preload: false,
    public: false,
    locked: false,
    frozen: false,
    unique: true,
    scene: false,
    disabled: false,
  },
  {
    name: 'Teleporter',
    image: {
      url: 'asset://Model.png',
    },
    model: 'asset://empty.glb',
    script: 'asset://Teleporter.js',
    scriptEntry: 'index.js',
    scriptFiles: {
      'index.js': 'asset://Teleporter.js',
    },
    scriptFormat: 'module',
    props: {
      teleporterId: 0,
      visible: true,
    },
    preload: false,
    public: false,
    locked: false,
    frozen: false,
    unique: true,
    scene: false,
    disabled: false,
  },
  {
    name: 'Mirror',
    image: {
      url: 'asset://Model.png',
    },
    model: 'asset://Model.glb',
    script: 'asset://Mirror.js',
    scriptEntry: 'index.js',
    scriptFiles: {
      'index.js': 'asset://Mirror.js',
    },
    scriptFormat: 'module',
    props: {
      width: 2,
      height: 2,
    },
    preload: false,
    public: false,
    locked: false,
    frozen: false,
    unique: true,
    scene: false,
    disabled: false,
  },
  {
    name: 'Spawn',
    image: {
      url: 'asset://Model.png',
    },
    model: 'asset://empty.glb',
    script: 'asset://Spawn.js',
    scriptEntry: 'index.js',
    scriptFiles: {
      'index.js': 'asset://Spawn.js',
    },
    scriptFormat: 'module',
    props: {
      teleporterId: 0,
      visible: true,
    },
    preload: false,
    public: false,
    locked: false,
    frozen: false,
    unique: true,
    scene: false,
    disabled: false,
  },
  {
    name: 'Image',
    image: {
      url: 'asset://Image.png',
    },
    model: 'asset://Image.glb',
    script: 'asset://Image.js',
    scriptEntry: 'index.js',
    scriptFiles: {
      'index.js': 'asset://Image.js',
    },
    scriptFormat: 'module',
    props: {
      width: 0,
      height: 2,
      fit: 'cover',
      image: null,
      transparent: false,
      lit: false,
      shadows: true,
      placeholder: {
        type: 'image',
        url: 'asset://Image.png',
      },
    },
    preload: false,
    public: false,
    locked: false,
    frozen: false,
    unique: true,
    scene: false,
    disabled: false,
  },
  {
    name: 'Video',
    image: {
      url: 'asset://Video.png',
    },
    model: 'asset://Video.glb',
    script: 'asset://Video.js',
    scriptEntry: 'index.js',
    scriptFiles: {
      'index.js': 'asset://Video.js',
    },
    scriptFormat: 'module',
    props: {
      width: 0,
      height: 2,
      fit: 'cover',
      url: null,
      loop: true,
      autoplay: true,
      transparent: false,
      lit: false,
      shadows: true,
      placeholder: {
        type: 'video',
        url: 'asset://Video.mp4',
      },
    },
    preload: false,
    public: false,
    locked: false,
    frozen: false,
    unique: true,
    scene: false,
    disabled: false,
  },
  {
    name: 'Text',
    image: {
      url: 'asset://Text.png',
    },
    model: 'asset://Text.glb',
    script: 'asset://Text.js',
    scriptEntry: 'index.js',
    scriptFiles: {
      'index.js': 'asset://Text.js',
    },
    scriptFormat: 'module',
    props: {
      width: 200,
      height: 200,
      text: 'Enter text...',
      fontSize: 20,
      fontWeight: 'bold',
      color: '#ffffff',
      transparent: false,
      lit: false,
      shadows: true,
    },
    preload: false,
    public: false,
    locked: false,
    frozen: false,
    unique: true,
    scene: false,
    disabled: false,
  },
  {
    name: 'Webview',
    image: {
      url: 'asset://Webview.png',
    },
    model: 'asset://Webview.glb',
    script: 'asset://Webview.js',
    scriptEntry: 'index.js',
    scriptFiles: {
      'index.js': 'asset://Webview.js',
    },
    scriptFormat: 'module',
    props: {
      url: 'https://www.youtube.com/embed/jfKfPfyJRdk?autoplay=1',
    },
    preload: false,
    public: false,
    locked: false,
    frozen: false,
    unique: true,
    scene: false,
    disabled: false,
  },
]
